# CHAT MESSAGE TYPES
USER_LEFT = "user_left"
USER_JOINED = "user_joined"
MESSAGE_ADDED = "message_added"
ALL_MESSAGE_TYPES = [USER_LEFT, USER_JOINED, MESSAGE_ADDED]

# CHAT CHANNELS PREFIXED
PERSONAL_CHANNEL_PREFIX = "personal"
